// This file is generated by Firebase Studio.
'use server';

/**
 * @fileOverview This file contains the Genkit flow for recommending treatment and preventative actions
 * based on disease diagnosis, integrating weather and IoT data.
 *
 * - recommendTreatment - A function that handles the treatment recommendation process.
 * - RecommendTreatmentInput - The input type for the recommendTreatment function.
 * - RecommendTreatmentOutput - The return type for the recommendTreatment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendTreatmentInputSchema = z.object({
  diseaseName: z.string().describe('The name of the diagnosed disease.'),
  severityLevel: z.string().describe('The severity level of the disease (e.g., low, medium, high).'),
  temperature: z.number().describe('The current temperature in Celsius.'),
  humidity: z.number().describe('The current humidity percentage.'),
  soilMoisture: z.number().describe('The current soil moisture level (e.g., low, medium, high).'),
  cropType: z.string().describe('The type of crop affected by the disease.'),
});
export type RecommendTreatmentInput = z.infer<typeof RecommendTreatmentInputSchema>;

const RecommendTreatmentOutputSchema = z.object({
  treatmentRecommendations: z.string().describe('Recommended treatments for the disease, considering weather and IoT data.'),
  preventativeActions: z.string().describe('Preventative actions to take based on current conditions.'),
});
export type RecommendTreatmentOutput = z.infer<typeof RecommendTreatmentOutputSchema>;

export async function recommendTreatment(input: RecommendTreatmentInput): Promise<RecommendTreatmentOutput> {
  return recommendTreatmentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendTreatmentPrompt',
  input: {schema: RecommendTreatmentInputSchema},
  output: {schema: RecommendTreatmentOutputSchema},
  prompt: `You are an expert agricultural advisor. A farmer is facing a disease outbreak in their field and needs your advice.

  Here's the information you have:
  - Disease: {{{diseaseName}}} (Severity: {{{severityLevel}}})
  - Crop Type: {{{cropType}}}
  - Current Temperature: {{{temperature}}}°C
  - Current Humidity: {{{humidity}}}%
  - Soil Moisture: {{{soilMoisture}}}

  Based on this information, provide clear and concise treatment recommendations and preventative actions the farmer should take.
  Consider how the temperature, humidity, and soil moisture might affect the disease and the effectiveness of different treatments.

  Format your response as follows:

  Treatment Recommendations: [Specific treatments, including product names and application instructions]
  Preventative Actions: [Steps the farmer can take to prevent further spread or future outbreaks]`,
});

const recommendTreatmentFlow = ai.defineFlow(
  {
    name: 'recommendTreatmentFlow',
    inputSchema: RecommendTreatmentInputSchema,
    outputSchema: RecommendTreatmentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
